spring.application.name=JWT_API

server.port=${PORT:8080}

spring.datasource.url= jdbc:postgresql://ep-empty-brook-a9jae0o0-pooler.gwc.azure.neon.tech/wellbeing_Db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4kRUqFOdMKg6

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect